# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI builds on master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 2
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Set up JDK 
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build with Gradle
      run: ./gradlew build
